import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { useRouter } from "next/router";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { useEffect, useState } from "react";
import NavbarHome from "@/components/nav";
import SearchBarHome from "./(homepage)/home/components/searchBarHomePage";
import Navbar from "./(homepage)/hotels/components/nav";
import HeaderLayout from "@/components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Đặt phòng khách sạn",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {/* <HeaderLayout /> */}
          <div className=" bg-gray-50">{children}</div>
          {/* <footer>
          <Footer />
        </footer> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
